name: CI

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Run unit tests
        run: npm run test:unit -- --run

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npm run test:e2e

      - name: Upload Playwright report on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Upload test results on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
          retention-days: 7

  # Optional: Matrix strategy for testing multiple Node versions
  # Uncomment to enable multi-version testing
  #
  # test-matrix:
  #   name: Test (Node ${{ matrix.node }})
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node: [18, 20, 21]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node }}
  #         cache: 'npm'
  #     
  #     - name: Install dependencies
  #       run: npm ci
  #     
  #     - name: Type check
  #       run: npm run typecheck
  #     
  #     - name: Lint
  #       run: npm run lint
  #     
  #     - name: Run unit tests
  #       run: npm run test:unit -- --run
  #     
  #     - name: Install Playwright browsers
  #       run: npx playwright install --with-deps
  #     
  #     - name: Run E2E tests
  #       run: npm run test:e2e
